[project]
name = "inspirehepmcp"
version = "0.1.0"
description = "InspireHEP Model Context Protocol server - Search and manage high energy physics papers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]
